version: '3.8'

services:
  skillab-analysis:
    container_name: ${APP_NAME}
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    build: .
    environment:
      - API_BASE_URL=https://skillab-tracker.csd.auth.gr/api
    ports:
      - "8873:8872"
    networks:
      - shared-net
    labels:
      io.portainer.accesscontrol.teams: skillab-all
    restart: unless-stopped

networks:
  shared-net:
    external: true